easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\About
        - App\Entity\Performance
        - App\Entity\Prices
        - App\Entity\Contact

